services:
  # 1. Database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: course_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: course_db
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d # Script tạo bảng lúc đầu
      - pgdata:/var/lib/postgresql/data       # LƯU DỮ LIỆU BỀN VỮNG (Mới thêm)

  # 2. Redis (Cache & Check Slot nhanh)
  redis:
    image: redis:alpine
    container_name: course_redis
    ports:
      - "6379:6379"

  # 3. Zookeeper (Quản lý Kafka) - MỚI THÊM
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: course_zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # 4. Apache Kafka (Message Queue xử lý tải cao) - MỚI THÊM
  kafka:
    image: bitnami/kafka:latest
    container_name: course_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # 5. Backend (Node.js)
  server:
    build: ./server
    container_name: course_api
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - KAFKA_BROKER=kafka:9092  # Server biết địa chỉ Kafka (Mới thêm)
      - DB_USER=admin
      - DB_PASS=password123
      - DB_NAME=course_db
    depends_on:
      - postgres
      - redis
      - kafka

  # 6. Frontend (React Vite)
  client:
    build: ./client
    container_name: course_ui
    ports:
      - "3000:5173" # Map cổng 3000 máy thật vào 5173 container
    volumes:
      - ./client/src:/app/src # Hot-reload: Sửa code thấy ngay
    depends_on:
      - server

# Khai báo Volume để lưu trữ dữ liệu DB
volumes:
  pgdata: